name: deploy static
on:
    push:
        branches:
            - master
jobs:
    build:
        name: deploy tetris-calc
        runs-on: ubuntu-latest
        steps:
        - name: publish files
          uses: appleboy/ssh-action@v0.1.10
          with:
            host: ${{secrets.HOST}}
            username: ${{secrets.USER_NAME}}
            key: ${{secrets.SSH_KEY}}
            script: |
                sudo su
                cd /var/www/html/group-class
                
                sudo git pull
                sudo systemctl restart nginx




    